name: ipinfo tests

on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ '1.17.x', '1.18.x', '1.19.x' ]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go ${{ matrix.go-version }}
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: Install dependencies
                run: go get ./cmd/ipinfo

            -   name: Test
                run: go test -tags integration -json -v ./... > TestResults-${{ matrix.go-version }}.json

            -   name: Upload Go ${{ matrix.go-version }} test results
                uses: actions/upload-artifact@v3
                with:
                    name: Go-results-${{ matrix.go-version }}
                    path: TestResults-${{ matrix.go-version }}.json
