name: ipinfo tests and build

on:
    push:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ '1.17.x', '1.18.x', '1.19.x', '1.20.x', '1.21.x', '1.22.x' ]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go ${{ matrix.go-version }}
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: Install dependencies
                run: go get ./cmd/ipinfo

            -   name: Test
                run: go test -tags integration -json -v ./... > TestResults-${{ matrix.go-version }}.json

            -   name: Upload Go ${{ matrix.go-version }} test results
                uses: actions/upload-artifact@v3
                with:
                    name: test-results-${{ matrix.go-version }}
                    path: TestResults-${{ matrix.go-version }}.json

    build:
        needs: test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform: [ 'windows', 'darwin', 'linux' ]
                architecture: [ 'amd64', 'arm64' ]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.19.1

            -   name: Install dependencies
                run: go get ./cmd/ipinfo

            -   name: Build application for ${{ matrix.platform }}
                run: rm -rf ./build/bin/* ; bash ./build.bash ${{ matrix.platform }}-${{ matrix.architecture }}

            -   name: Executable upload ${{ matrix.platform }}-${{ matrix.architecture }}
                uses: actions/upload-artifact@v3
                with:
                    name: ipinfo-${{ matrix.platform }}-${{ matrix.architecture }}
                    path: ./build/bin/
